export { default as Portfolio } from './Portfolio/Portfolio'
export { default as Landing } from './Landing'
export { default as Services } from './Our Services/Services'
export {default as About } from './About Us/About'
export { default as Story } from './Our Story/Story'
export { default as Talk } from './Talk To Us/Talk'
export { default as Navbar } from './Navbar/Navbar'
export { default as Test } from './Testor/Test'
export { default as SVGPathGenerator } from './Main Page/SVGPathGenerator'
export { default as SectionOne } from './Main Page/SectionOne'
export { default as CardOne } from './Main Page/CardOne'
export { default as SectionTwo } from './Main Page/SectionTwo'
export { default as Saz } from './Main Page/Saz'
export { default as Twilio } from './Main Page/Twilio'
export { default as ContactUs } from './Talk To Us/ContactUs'
export { default as Navy } from './Navbar/Navy'
export { default as SectionFiveOne } from './Main Page/SectionFiveOne'
export { default as InfinateScroller } from './Our Services/InfinateScroller'
export { default as AboutSection } from './About Us/AboutSection'
export { default as TalkyOne } from './Talk To Us/TalkyOne'